services:
  protonmail-bridge:
    image: ghcr.io/videocurio/proton-mail-bridge:latest
    container_name: protonmail-bridge
    restart: unless-stopped
    ports:
      - "0.0.0.0:1143:143/tcp"
      - "0.0.0.0:1025:25/tcp"
    volumes:
      - /data/protonmail-data:/root
