services:
  consul-agent:
    image: hashicorp/consul:${CONSUL_VERSION:-1.22.3}
    container_name: consul-agent
    hostname: ${CONSUL_NODE_NAME:-consul-agent}
    restart: unless-stopped
    network_mode: host
    volumes:
      - consul-data:/consul/data
    environment:
      - CONSUL_CA_CERT_B64=${CONSUL_CA_CERT_B64}
    configs:
      - source: consul_config
        target: /consul/config/consul.hcl
    entrypoint: |
      sh -c '
        echo "Preparing certs..."
        mkdir -p /consul/certs
        echo "$$CONSUL_CA_CERT_B64" | base64 -d > /consul/certs/consul-agent-ca.pem
        echo "Certs ready."
        exec consul agent -config-file=/consul/config/consul.hcl -retry-join=${CONSUL_SERVER_IP}
      '

volumes:
  consul-data:

configs:
  consul_config:
    content: |
      datacenter    = "${CONSUL_DATACENTER}"
      data_dir      = "/consul/data"
      log_level     = "${CONSUL_LOG_LEVEL}"
      server        = false
      client_addr   = "0.0.0.0"
      bind_addr      = "{{ GetInterfaceIP \"${NETWORK_INTERFACE}\" }}"
      advertise_addr = "{{ GetInterfaceIP \"${NETWORK_INTERFACE}\" }}"
      rejoin_after_leave = true

      # Gossip Encryption
      encrypt                 = "${CONSUL_GOSSIP_KEY}"
      encrypt_verify_incoming = true
      encrypt_verify_outgoing = true

      # RPC TLS
      tls {
        defaults {
          ca_file         = "/consul/certs/consul-agent-ca.pem"
          verify_outgoing = true
        }
        internal_rpc {
          verify_server_hostname = true
        }
      }

      auto_encrypt {
        tls = true
      }

      connect { enabled = true }
      ports { grpc = 8502 }

      performance {
        raft_multiplier = 1
      }

      recursors = ["8.8.8.8", "1.1.1.1"]
